In [1]:
lista = [1,2,3,4,5,14]

In [2]:
len(lista)

6

In [3]:
lista[3] + lista[-1]

18

In [4]:
lista_nombre = ["Luis Cueva","Ana Zum" , "Carmen Rojas"]

In [5]:
lista_nombre

['Luis Cueva', 'Ana Zum', 'Carmen Rojas']

In [7]:
def f_diploma_link(nombre):
    link = "http://www.tuNombreEs."+ nombre + ".com"
    return link

In [8]:
for name in lista_nombre:
    print(f_diploma_link(name))

http://www.tuNombreEs.Luis Cueva.com
http://www.tuNombreEs.Ana Zum.com
http://www.tuNombreEs.Carmen Rojas.com


# Diccionario

In [10]:
mi_diccionario = {"Nombre" : "Luis" , "Apellido":"Cueva " , "Edad":25 }

In [20]:
print(mi_diccionario.keys(), mi_diccionario.values())

dict_keys(['Nombre', 'Apellido', 'Edad']) dict_values(['Luis', 'Cueva ', 25])


In [18]:
for key in list(mi_diccionario.keys()):
    print(mi_diccionario[key])

Luis
Cueva 
25


In [21]:
import numpy as np

In [22]:
x = [0,1,2,3,4,5]

In [23]:
x

[0, 1, 2, 3, 4, 5]

In [24]:
y = np.array(x)

In [25]:
y

array([0, 1, 2, 3, 4, 5])

In [30]:
print("x es una {}".format(type(x)) , "y es un {}".format( type(y)))

x es una <class 'list'> y es un <class 'numpy.ndarray'>


In [35]:
y.T-30

array([-30, -29, -28, -27, -26, -25])

In [37]:
p = np.array([[1,2,3],[4,5,6]])

In [39]:
print(p)

[[1 2 3]
 [4 5 6]]


In [40]:
p.flatten()

array([1, 2, 3, 4, 5, 6])

# Pandas

In [41]:
import pandas as pd

In [56]:
data = pd.read_csv("train.csv")

In [58]:
data.head(10)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [67]:
edad = data["Age"]

In [69]:
 sum(edad.isnull())

177

In [72]:
pd.crosstab(index=data["Survived"],columns=data["Sex"])

Sex       female  male
Survived              
0             81   468
1            233   109

In [75]:
data.head(11).to_excel("data_10.xls")

In [ ]:
data_2 =pd.read_excel

In [76]:
# Reading JSON
pd.read_json('https://api.github.com/repos/pydata/pandas/issues?per_page=5')

assignee assignees author_association  \
0       NaN        []               NONE   
1       NaN        []        CONTRIBUTOR   
2       NaN        []               NONE   
3       NaN        []        CONTRIBUTOR   
4       NaN        []        CONTRIBUTOR   

                                                body closed_at  comments  \
0  #### Code Sample\r\n```python\r\nfrom pandas i...       NaT         0   
1  #### Code Sample, a copy-pastable example if p...       NaT         1   
2  #### Code Sample, a copy-pastable example if p...       NaT         0   
3  `index.dt` --> `self` for `DatetimeIndex`, `Ti...       NaT         0   
4  - [x] closes #18367\r\n\r\nThis breaks out mel...       NaT         0   

                                        comments_url          created_at  \
0  https://api.github.com/repos/pandas-dev/pandas... 2017-11-22 18:42:51   
1  https://api.github.com/repos/pandas-dev/pandas... 2017-11-22 16:56:13   
2  https://api.github.com/repos/pandas-dev/pandas... 2017-11-22 16:49:59   
3  https://api.github.com/repos/pandas-dev/pandas... 2017-11-22 16:37:45   
4  https://api.github.com/repos/pandas-dev/pandas... 2017-11-22 16:08:28   

                                          events_url  \
0  https://api.github.com/repos/pandas-dev/pandas...   
1  https://api.github.com/repos/pandas-dev/pandas...   
2  https://api.github.com/repos/pandas-dev/pandas...   
3  https://api.github.com/repos/pandas-dev/pandas...   
4  https://api.github.com/repos/pandas-dev/pandas...   

                                            html_url  \
0  https://github.com/pandas-dev/pandas/issues/18432   
1  https://github.com/pandas-dev/pandas/issues/18431   
2  https://github.com/pandas-dev/pandas/issues/18430   
3    https://github.com/pandas-dev/pandas/pull/18429   
4    https://github.com/pandas-dev/pandas/pull/18428   

                         ...                          locked milestone number  \
0                        ...                           False       NaN  18432   
1                        ...                           False       NaN  18431   
2                        ...                           False       NaN  18430   
3                        ...                           False       NaN  18429   
4                        ...                           False       NaN  18428   

                                        pull_request  \
0                                                NaN   
1                                                NaN   
2                                                NaN   
3  {'url': 'https://api.github.com/repos/pandas-d...   
4  {'url': 'https://api.github.com/repos/pandas-d...   

                                   repository_url  state  \
0  https://api.github.com/repos/pandas-dev/pandas   open   
1  https://api.github.com/repos/pandas-dev/pandas   open   
2  https://api.github.com/repos/pandas-dev/pandas   open   
3  https://api.github.com/repos/pandas-dev/pandas   open   
4  https://api.github.com/repos/pandas-dev/pandas   open   

                                               title          updated_at  \
0  Attempting a groupby over a CategoricalIndex f... 2017-11-22 18:42:51   
1  BUG: date_range is inconsistent when given mix... 2017-11-22 16:57:18   
2              pd.rolling_corr produces wrong result 2017-11-22 16:49:59   
3           implement .dt accessor for Index classes 2017-11-22 16:37:45   
4                         melt test is in own module 2017-11-22 16:08:28   

                                                 url  \
0  https://api.github.com/repos/pandas-dev/pandas...   
1  https://api.github.com/repos/pandas-dev/pandas...   
2  https://api.github.com/repos/pandas-dev/pandas...   
3  https://api.github.com/repos/pandas-dev/pandas...   
4  https://api.github.com/repos/pandas-dev/pandas...   

                                                user  
0  {'login': 'ekisslinger', 'id': 33908309, 'avat...  
1  {'login': 'jschendel', 'id': 5332445, 'avatar_...  
2  {'l

In [78]:
import requests

In [79]:
data = requests.get("https://listado.mercadolibre.com.pe/sonic#D[A:sonic]")

In [80]:
print(data)

<Response [200]>


In [81]:
data

<Response [200]>

In [82]:
data.content

b'\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<!doctype html>\n<html class="no-js" lang="es-PE" data-site="MPE"\n      data-country="PE"\n      data-device="desktop">\n\n<head prefix="">\n\t<title>Sonic en Mercado Libre Per\xc3\xba\n</title>\n\n\t<link rel="preconnect" href="//analytics.mlstatic.com"/>\n\t<link rel="preconnect" href="//resources.mlstatic.com"/>\n\t<link rel="preconnect" href="//static.mlstatic.com"/>\n\t<link rel="preconnect" href="https://www.google-analytics.com"/>\n\t<link rel="preconnect" href="https://www.google.com"/>\n\t<link rel="preconnect" href="https://http2.mlstatic.com"/>\n\t\n\t\t<link rel="preconnect" href="https://www.google.com.pe"/>\n\t\n\n\n\t\n\t\t<link rel="preconnect" href="https://stats.g.doubleclick.net"/>\n\t\n\n\n\t\n\t\n\t\t<link rel="preconnect" href="//analytics.mercadolibre.com.pe"/>\n\t\n\n\t\n\t\t<link rel="preconnect" href="//mpe-s1-p.mlstatic.com"/>\n\t\t<link rel="preconnect" href="//mpe-s2-p.mlstatic.com"/>\n\t\n\n\n\t\n\n\t\n\n\t\n\t\t<script>d